import Mathlib

/-!
# ElGamal Encryption in Lean 4

This file is a small exploration of ElGamal in Lean 4.
We formalize the encryption scheme and prove three
algebraic/probabilistic properties:

1. **Correctness**: decryption inverts encryption.
2. **Homomorphic property**: component-wise ciphertext multiplication corresponds
   to multiplying plaintexts and adding randomness.
3. **Random blinding**: multiplying a uniform distribution by a fixed group
   element preserves uniformity. This is the key probabilistic lemma behind
   ElGamal's IND-CPA security.

## Background

ElGamal is usually presented over a cyclic group G with generator g. Writing
`m ∈ G` for the plaintext message to be encrypted:

- **Key generation**: choose secret x ∈ ℤ; publish pk = g^x.
- **Encryption**: choose random r ∈ ℤ; output (g^r, pk^r * m).
- **Decryption**: given (c₁, c₂), compute c₂ * (c₁^x)⁻¹.

In this file, Properties A and B are formalized over `CommGroup G` with `g` a
fixed element of `G` rather than a typeclass-supplied generator; the
construction then takes place in the cyclic subgroup generated by `g`, so the
proofs do not require `g` to generate all of `G`. Property C is proved
separately for an arbitrary finite group, since the random blinding lemma
only uses that right multiplication by a fixed element is a bijection.
Exponents are integers (`ℤ`), using Lean's `zpow` (written `g ^ x` for `x : ℤ`).

## IND-CPA security

**IND-CPA security** (indistinguishability under chosen-plaintext attack) is
the standard semantic-security notion for public-key encryption: no efficient
adversary, given a public key and a ciphertext encrypting one of two
plaintexts it chose, can guess which plaintext was encrypted with probability
noticeably better than 1/2.

The **DDH assumption** (decisional Diffie-Hellman) says: in a cyclic group
`G` with generator `g`, given `(g^a, g^b, T)` for uniformly random exponents
`a, b`, no efficient adversary can distinguish `T = g^(a*b)` from `T` drawn
independently and uniformly at random in `G` with probability noticeably
better than 1/2.

Property C is the key probabilistic ingredient in the proof that ElGamal is
IND-CPA secure under DDH.
-/

namespace ElGamal

/-! ## Definitions

We define ElGamal over an abstract commutative group `G`. The group operation
is written multiplicatively. Exponents (secret keys, randomness) are integers. -/

variable {G : Type*} [CommGroup G]

/-- The public key derived from base element `g` and secret key `x`. -/
def publicKey (g : G) (x : ℤ) : G := g ^ x

/-- Encrypt message `m` under public key `pk` with base element `g` and randomness `r`.
Returns a ciphertext pair (c₁, c₂) = (g^r, pk^r * m). -/
def encrypt (g pk m : G) (r : ℤ) : G × G :=
  (g ^ r, pk ^ r * m)

/-- Decrypt ciphertext (c₁, c₂) using secret key `x`.
Computes c₂ * (c₁^x)⁻¹, recovering the original message. -/
def decrypt (x : ℤ) (c : G × G) : G :=
  c.2 * (c.1 ^ x)⁻¹

/-! ## A. Correctness

Decryption recovers the plaintext. The proof is pure group algebra:

    decrypt(x, encrypt(g, g^x, m, r))
    = (g^x)^r * m * ((g^r)^x)⁻¹        -- unfold definitions
    = g^(xr) * m * (g^(rx))⁻¹           -- zpow_mul: (g^a)^b = g^(ab)
    = g^(xr) * m * (g^(xr))⁻¹           -- mul_comm on ℤ: rx = xr
    = m * g^(xr) * (g^(xr))⁻¹           -- mul_comm in CommGroup
    = m                                   -- cancellation: a * a⁻¹ = 1
-/

theorem decrypt_encrypt (g m : G) (x r : ℤ) :
    decrypt x (encrypt g (publicKey g x) m r) = m := by
  -- Unfold definitions; collapse (g^a)^b into g^(a*b) via zpow_mul.
  simp only [decrypt, encrypt, publicKey, ← zpow_mul]
  -- Goal: g^(x*r) * m * (g^(r*x))⁻¹ = m.
  -- Align the two exponents (r*x = x*r), move the inverse next to its partner
  -- via mul_right_comm (a * b * c = a * c * b), then cancel.
  rw [mul_comm r x, mul_right_comm, mul_inv_cancel, one_mul]

/-! ## B. Homomorphic Property

ElGamal is multiplicatively homomorphic: multiplying ciphertexts component-wise
produces a valid encryption of the product of the plaintexts (with the sum of
the randomness values).

    encrypt(g, pk, m₁, r₁) ⊗ encrypt(g, pk, m₂, r₂)
    = (g^r₁ * g^r₂,  pk^r₁ * m₁ * pk^r₂ * m₂)       -- component-wise product
    = (g^(r₁+r₂),    pk^(r₁+r₂) * (m₁ * m₂))        -- zpow_add + rearrange
    = encrypt(g, pk, m₁*m₂, r₁+r₂)

This property makes ElGamal malleable (an attacker can manipulate ciphertexts),
which is why ElGamal is NOT IND-CCA secure. But it is useful in applications
like homomorphic tallying in e-voting. -/

theorem encrypt_mul (g pk m₁ m₂ : G) (r₁ r₂ : ℤ) :
    ((encrypt g pk m₁ r₁).1 * (encrypt g pk m₂ r₂).1,
     (encrypt g pk m₁ r₁).2 * (encrypt g pk m₂ r₂).2)
      = encrypt g pk (m₁ * m₂) (r₁ + r₂) := by
  -- Unfold encrypt; split the pair equality into two component goals.
  simp only [encrypt, Prod.mk.injEq]
  refine ⟨?_, ?_⟩
  · -- First component: g^r₁ * g^r₂ = g^(r₁ + r₂), by zpow_add.
    rw [← zpow_add]
  · -- Second component: pk^r₁ * m₁ * (pk^r₂ * m₂) = pk^(r₁+r₂) * (m₁ * m₂).
    -- The interchange law a*b*(c*d) = a*c*(b*d) groups pk-powers together
    -- and messages together; then zpow_add combines pk^r₁ * pk^r₂.
    rw [mul_mul_mul_comm, ← zpow_add]

end ElGamal

/-! ## C. Random Blinding

In a finite group, multiplying a uniformly random element by any fixed element
preserves the uniform distribution.

Concretely, if `z` is sampled uniformly from `G`, then `z * m` is also uniform
for any fixed `m`. This holds because right multiplication by `m` is a bijection
on `G`, so it merely permutes the elements without changing their probabilities.

This is a key algebraic ingredient in ElGamal's semantic security proof. In the
IND-CPA reduction, the DDH assumption allows one to replace the masking term
`pk^r` by a computationally indistinguishable uniformly random group element
`z`; the ciphertext component then becomes `z * m_b`, which by this lemma is
uniform independently of the message `m_b`. Hence this component reveals no
information about the encrypted plaintext.

Unlike the correctness and homomorphic proofs, this lemma is a generic fact
about PMFs on a finite group, so it lives outside the `ElGamal` namespace.

We use Mathlib's `PMF G`, the type of *probability mass functions* on `G`
(discrete probability distributions). Here `PMF.uniformOfFintype G` is the
uniform distribution on a finite `G`, and
`PMF.map (· * m) (PMF.uniformOfFintype G)` is the distribution of `x * m`
when `x` is sampled uniformly from `G`. -/

theorem PMF.map_mul_uniformOfFintype_eq
    {G : Type*} [Group G] [Fintype G] [DecidableEq G] [Nonempty G] (m : G) :
    PMF.map (· * m) (PMF.uniformOfFintype G) = PMF.uniformOfFintype G := by
  -- Reduce to pointwise equality: both PMFs assign the same probability to
  -- every b ∈ G.
  ext b
  -- Expand PMF.map: (map f p) b = ∑' a, if b = a * m then p(a) else 0.
  rw [PMF.map_apply]
  -- Right-multiplication by m is a bijection, so b has a unique preimage
  -- a = b * m⁻¹. Rewrite the conditional with that.
  have preimage : ∀ a : G, (b = a * m) ↔ (a = b * m⁻¹) := fun a =>
    eq_comm.trans eq_mul_inv_iff_mul_eq.symm
  simp_rw [preimage]
  -- Only the term a = b * m⁻¹ survives the tsum; the rest is uniformity.
  rw [tsum_ite_eq]
  simp
